### ISSUE TITLE
The submodule 'website' is not functional and not rolled out

### ISSUE THREAD

**Issue by keyboardsurfer** [immopoly/immopoly#1]
The submodule mentioned above should be expanded in functionality and then rolled out to create new view of the immopoly website.

**Comment by mrschtief** [comment]
wurde von T und stevie gemacht ist jetzt im Master integriert

**Comment by stefanhoth** [comment]
Müssten wir das nicht noch als submodule in appengine reinhängen? Bisher ist doch noch manuelle Kopierarbeit deinerseits nötig, oder?

**Comment by mrschtief** [comment]
Nein wozu noch nen submodul? die Index.html liegt im war verzeichnis des appengine submodules
