### ISSUE TITLE
Neue Wohnungen auf der Karte markieren

### ISSUE THREAD

**Issue by stefanhoth** [immopoly/immopoly#12]
@mrschtief:
können wir neue Wohnungen auf der Karte besonders hervorheben? oder das alter des Exposes irgendwie darstellen?

**Comment by stefanhoth** [comment]
Die erste Frage ist vielleicht ob wir das wollen!?

Derzeit ist es doch so, dass es ein bißchen Ostern und Memory ist, nicht besetzte Wohnungen zu finden.

Es wäre imho eher eine gute Idee für ein Item für eine bestimmte Zeit/ein Skill besetzte Wohnungen zu erkennen.

**Comment by mrschtief** [comment]
fixed siehe #13
