### ISSUE TITLE
Wohnung wieder abgeben

### ISSUE THREAD

**Issue by stefanhoth** [immopoly/immopoly#14]
Es sollte möglich sein, die Maklerschaft für eine Wohnung wieder aufzugeben.

Das ist für andere Ideen für das Spielverhalten Vorraussetzung.

**Comment by stefanhoth** [comment]
@mrschtief:

+1 wir sollten hier eine Strafzahlung vorsehen

**Comment by keyboardsurfer** [comment]
Was haltet Ihr von einem Marktplatz für Wohnungen?

**Comment by stefanhoth** [comment]
Kurzfristig: Strafzahlung (Standard 2fach) und sofortige Freigabe

Langfristige Idee: Mehrfachmakler (Teilung von Kosten und Gewinn), Einzelauftrag kostet doppelt soviel bei der Übernahme

**Comment by mrschtief** [comment]
Kurzfristig möglich, als Freigabe zu markieren und Abgabe bei Anfrage eines anderen Maklers

**Comment by mrschtief** [comment]
backend neue Action implementiert ActionExposeRemove

siehe https://github.com/immopoly/immopoly/wiki/ImmopolyAPI

jetzt noch auf dem Client integrieren.

Strafe is momentan 4-fache Tagesmiete siehe Const.java

**Comment by mrschtief** [comment]
ich sitze hier dran am android client zum wieder reinkommen

**Comment by mrschtief** [comment]
fertich der button zeigt jetzt übernahme versuchen oder wohnung aufgeben an

**Comment by tobibo** [comment]
cool! 

_Sent via Hubroid_
