### ISSUE TITLE
Website aufhübschen und Mobilversion

### ISSUE THREAD

**Issue by stefanhoth** [immopoly/immopoly#15]
Ich hatte bereits einmal einen Grobentwurf für eine "hübschere" Webseite gemacht und @tobibi und @mrschtief gezeigt. Die Anpassung dessen an Mobilgeräte und der Feinschliff (Fonts/Farben) stünde noch aus, aber insgesamt wäre es relavtiv schnell fertig zustellen.

Dies wäre auch für neue Funktionen wie ein Changelog oder eine Anleitung hilfreich, die man dann einfach per Webview einblenden könnte.

**Comment by yncyrydybyl** [comment]
die webseite muss sich dann mehr an spieler richten. ich habe schon mal das grundgerüst übernommen.

**Comment by stefanhoth** [comment]
Finde es aber generell nicht schlecht, wenn wir die technischen Infos zum Projekt auch behalten. Passt zum OpenSource-Gedanken und hilft Immo, die App als API-Showcase zu featuren.

**Comment by mrschtief** [comment]
siehe #52
