### ISSUE TITLE
Heatmap für Städte/Regionen

### ISSUE THREAD

**Issue by stefanhoth** [immopoly/immopoly#17]
Es wäre irgendwie cool zu sehen, wo in der Stadt Leute noch nicht gewildert haben. Dazu böte sich eine Heatmap an, die die Konzentration der immopoly-Spieler in "heiße" und "kalte" Zonen übersetzt.

**Comment by stefanhoth** [comment]
@mrschtief
super idee, koennen wir auf der webseite machen, in der app haben wir die
daten nicht

**Comment by stefanhoth** [comment]
Man könnte es serverseitig als PNG erstellen und dann auch für Clients abrufbar machen. Aber das ist natürlich Zukunftsmusik.

**Comment by mrschtief** [comment]
setze ich gerade mit http://www.patrick-wied.at/static/heatmapjs/demo/maps_heatmap_layer/gmaps.php um

**Comment by mrschtief** [comment]
Datenformat :

{ max: 46, data: [{lat: 33.5363, lng:-117.044, count: 1},...] }

**Comment by mrschtief** [comment]
alle mal staunen...

http://immopoly.appspot.com/heatmap.html

stevie baut das noch in die richtige website unter statistik ein

**Comment by stefanhoth** [comment]
@mrschtief & ich: Haben seine Demo zusammen in die Livestats übertragen. Es ist live und sieht fucking awesome aus!

http://immopoly.org/livestats.html
