### ISSUE TITLE
Passwort vergessen

### ISSUE THREAD

**Issue by stefanhoth** [immopoly/immopoly#24]
@mrschtief:

Beim anmelden muss man seine emailadresse mit angeben, so dass man sich einen password reset link zuschicken lassen kann. Der Server bietet dann eine kleine Webseite zur neueingabe des passwortes

server:

user um email erweitern erweitern
tabelle für temporär gültige keys die an die reset url angehängt werden
"user/passwordrest?username=..&key=.." Action auf dem Server
app:
- button bei loginformular

**Comment by stefanhoth** [comment]
Ticket #7 als Duplikat geschlossen.

**Comment by mrschtief** [comment]
Problem: wir haben momentan keine Mailadresse der User

Lösung: entweder mit twitter oath #10 oder email im userobjekt

**Comment by mrschtief** [comment]
email ist ins profil hinzugefügt siehe https://github.com/immopoly/immopoly/issues/31#issuecomment-2060377 die Funktion kann jetzt implementiert werden

**Comment by mrschtief** [comment]
done ;) doku kommt morgen, die funktion ist aber schon benutzbar, es gibt einen experimentallogin auf der startseite

**Comment by mrschtief** [comment]
doku : https://github.com/immopoly/immopoly/wiki/ImmopolyAPI

Ich entferne jetzt mal den Server-Api tag

**Comment by mrschtief** [comment]
ist auf iphone backend implementiert fehlt nur noch android. dort gibt es den entsprechenden issue

https://github.com/immopoly/android/issues/39
