### ISSUE TITLE
location spoofing

### ISSUE THREAD

**Issue by stefanhoth** [immopoly/immopoly#26]
@mrschtief:

Es wurde berichtet das der Spitzenreiter @fanieldinke location spoofing betreibt. is ja nich schlimm so lange wir das erlauben. aber jetzt wirds zeit das mal zu beheben. 
Wenns nach mir geht muss er auch für dieses issue zahlen was haltet ihr von 100.000?

**Comment by stefanhoth** [comment]
@deadfalkon

Das kann der gar nicht. Der hat nichtmal root auf seinem Telefon. Der ist einfach nur der einzige da unten in Neukölln und nährt sich an der Gentrifizierung

**Comment by stefanhoth** [comment]
@mrschtief:

;) na ich bau mal in den nächtlichen cronjob ne Geschwindigkeitsmessung ein, und wenn zwischen exposes im abstand von 2km mehr als 100km/h erreicht worden sind, melden wir das erstmal nach Flensburg

**Comment by stefanhoth** [comment]
@tobibo

Das kann jeder :), gibt apps die den LocationProvider simulieren und mit denen man die Location ändern kann.

https://market.android.com/details?id=com.lexa.fakegps

sollten wir verhindern, gerade in Bezug auf mögliche featuers wie beamen oder taxi um die location kurz zeitig zu ändern.

**Comment by stefanhoth** [comment]
@keyboardsurfer

Denke dabei an eine eigene Bibliothek, die wir als jar anbieten und entsprechende Sicherheitsmechanismen dorthin verlagern.

**Comment by stefanhoth** [comment]
@keyboardsurfer closed

**Comment by stefanhoth** [comment]
@mrschtief: kann man das irgendwie so abkapseln das man einen eigenen locationprovider
hat, der nur realistische werte liefert?

**Comment by stefanhoth** [comment]
@keyboardsurfer:
So in etwa, ja. Wir können eine Plausibilitätsprüfugn der Ortsangaben vornehmen und sie dann von der eigenen Bibliothek aus an den Server schicken.

**Comment by stefanhoth** [comment]
@mrschtief:

hey wir machen das auf dem Server, und geben dann einfach ne
entsprechende Exception mit dem Text und code zurück, dann brauchen
wir in der App nichts machen und haben gleich ne Lösung fürs iphone
später

**Comment by stefanhoth** [comment]
@keyboardsurfer reopen

**Comment by mrschtief** [comment]
Ich habe jetzt mal folgenden code commited:
- beim übernahmeversuch werden die übernahmen der letzten stunde gecheckt
- ist ein exposes weiter entfernt als man es mit 100km/h erreichen könnte gibt es eine Spoofing alert Exception

Ich habe es noch nicht deployed.
Diskussionen und Tests am Samstag dazu

**Comment by mrschtief** [comment]
fertig und getestet, die app zeigt einen Hinweiß an "Da warst du aber zu schnell"

**Comment by mrschtief** [comment]
reopened, anscheinend ist der neue Exception Code nicht kompatibel mit den alten versionen. siehe #38

**Comment by mrschtief** [comment]
ich hatte den spoofing alert beim letzten Treffen mal eingebaut und sehe jetzt etlich alerts im log, alle mit geschwindigkeiten bis 100m/s.... müssen wir nochmal drüber sprechen, ich habs erstmal wieder rausgenommen

**Comment by tobibo** [comment]
Wie ist der Stand hier?

**Comment by mrschtief** [comment]
ist momentan auf serverseite deaktiviert bis die wartezeit pro bernahme
implementiert ist
Am 16.11.2011 22:20 schrieb "tosa" <
reply@reply.github.com

**Comment by keyboardsurfer** [comment]
Ist AFAIK implementiert.
