### ISSUE TITLE
appengine lokal testen

### ISSUE THREAD

**Issue by stefanhoth** [immopoly/immopoly#27]
@tresbjorn: 
Um die AppEngine lokal laufen zu lassen habe ich kurzerhand mal 2 Konstanten
in WebHelper (hmm) angelegt und an den relevanten Stellen benutzt:

// appengine on immopoly.appspot.com
public static final String SERVER_URL_PREFIX = "http://immopoly.appspot.com";
public static final String SERVER_HTTPS_URL_PREFIX = "https://immopoly.appspot.com";
// appengine on emulator host (http only)
// public static final String SERVER_URL_PREFIX = "http://10.0.2.2:8888";
// public static final String SERVER_HTTPS_URL_PREFIX = "http://10.0.2.2:8888";

Läuft!

Ok so? Einwände?
Sonst schick ich das mal hoch...

**Comment by stefanhoth** [comment]
@mrschtief:

perfekt alder, wir müssen uns eh noch gedanken um einen IS24
MockServer machen, der immer die gleiche Testantwort für die
Entwicklung zurückliefert

**Comment by stefanhoth** [comment]
@tresbjorn:

So, ist drin.
(Die Top 20 Makler: 1. björn 5000,00 EUR ;-)

**Comment by mrschtief** [comment]
Ich öffne dieses Issue nochmal, da wir noch keinen Mockserver oder irgendeine Strategie haben

**Comment by keyboardsurfer** [comment]
Backend wird neu geschrieben.
