### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by stefanhoth** [immopoly/immopoly#28]
@tobibo

Ich würde gerne Google Analytics für die immopoly.appspot.com index seite einbauen. Bitte um Diskussion, Votes oder Flamewars!!!

**Comment by stefanhoth** [comment]
@keyboardsurfer

+1 Nutzeranalyse FTW. was haltet ihr davon, das auch in der App zu machen?

**Comment by stefanhoth** [comment]
@tobibo

Finde ich gut.

**Comment by stefanhoth** [comment]
@mrschtief

in der index html datei eingebaut. deploye ich auf dem #cccamp

habe die labels auf client angepasst, hat jemand erfahrung wie man google analytics in ne app baut?

**Comment by stefanhoth** [comment]
@tobibo

Jepp, kann ich machen, hatte ich auch schon mal angefangen, aber dann sein
gelassen. Wir sollten nur genau berlegen was wir eigentlich tracken wollen.

Schlage vor simple events wie:
- Start der App
- Wohnung anschauen
  - start und stop messen, also Zeit bekommen wie lange angeschaut
- Wohung bernahme
  - erfolg
  - nicht
- Wohnung sharen
  - aus Webview
  - aus Wohnungserfolg
- Wechsel zu Dashboard
- Hilfe Button aus Dashboard/Map/Login
- ffnen der Wohnungs aus Portifolio map

Ergänzungen ?

**Comment by stefanhoth** [comment]
@tobibo closed

**Comment by stefanhoth** [comment]
@tobibo

Könnt ja mal Dinge hinzufügen hier!

https://spreadsheets.google.com/spreadsheet/ccc?key=0AgApn6ffQ1KIdFVyX1lBYXdCSjk5NWZwd3BEbUsydVE&hl=en_GB#gid=0

**Comment by stefanhoth** [comment]
@tobibo reopen

**Comment by stefanhoth** [comment]
@mrschtief

ich bin d'accord mit dem spreadsheet

**Comment by tobibo** [comment]
done. Alle die Zugang haben schaut mal ob noch was fällt also was wir noch tracken sollten.
