### ISSUE TITLE
Provisionberechnung am 09.08.11 fehlerhaft

### ISSUE THREAD

**Issue by stefanhoth** [immopoly/immopoly#29]
@rob-bors

Hallo,
heute nacht wurden nur die letzten 2 vermieteten Wohnungen übernommen. Spielername: "immorob".
09.08.2011 0:21 Uhr 2 Objekte wurden vermietet und deren provision übernommen.
09.08.2011 0:20 Uhr zig Objekten wurden vermietet und Provision nicht übernommen...

**Comment by stefanhoth** [comment]
@mrschtief:

es gab heute nacht wieder etliche sockettimeouts beim verbindungsaufbau zur
is24 api

z.b.

2011-08-09 00:47:05.277 org.immopoly.appengine.WebHelper getHttpData:
request failed java.net.SocketTimeoutException: Timeout while fetching:
http://rest.immobilienscout24.d

gab es wieder eine downtime?

wir brauchen eine idee wie wir fehlertoleranter werden... ich schau mal nach
transaktionen im backend, damit wir ein rollback machen koennen.

**Comment by stefanhoth** [comment]
@mrschtief

Also die Berechnung von immorob lief normal durch, nur 2 Wohnungen wurden vermietet von 213 !!1 ;)

2011-08-09 00:21:11.990 org.immopoly.appengine.CronjobServlet doGet: starte Mietberechnung
I 2011-08-09 00:21:13.347 org.immopoly.appengine.CronjobServlet doGet: User immorob
I 2011-08-09 00:21:13.472 org.immopoly.appengine.CronjobServlet doGet: User immorob Exposes #213
I 2011-08-09 00:21:13.473 org.immopoly.appengine.CronjobServlet doGet: 1 60286281
I 2011-08-09 00:21:14.015 org.immopoly.appengine.CronjobServlet doGet: 2 61089734
I 2011-08-09 00:21:14.181 org.immopoly.appengine.CronjobServlet doGet: 3 58654107
I 2011-08-09 00:21:14.351 org.immopoly.appengine.CronjobServlet doGet: 4 61023015
I 2011-08-09 00:21:14.511 org.immopoly.appengine.CronjobServlet doGet: 5 60552979
I 2011-08-09 00:21:14.716 org.immopoly.appengine.CronjobServlet doGet: 6 60600781
I 2011-08-09 00:21:14.881 org.immopoly.appengine.CronjobServlet doGet: 7 56949828
I 2011-08-09 00:21:15.053 org.immopoly.appengine.CronjobServlet doGet: 8 60227282
I 2011-08-09 00:21:15.213 org.immopoly.appengine.CronjobServlet doGet: 9 61112364
I 2011-08-09 00:21:15.475 org.immopoly.appengine.CronjobServlet doGet: 10 60956621
I 2011-08-09 00:21:15.667 org.immopoly.appengine.CronjobServlet doGet: 11 60575631
I 2011-08-09 00:21:15.910 org.immopoly.appengine.CronjobServlet doGet: 12 56859986
I 2011-08-09 00:21:16.267 org.immopoly.appengine.CronjobServlet doGet: 13 60693155
I 2011-08-09 00:21:16.467 org.immopoly.appengine.CronjobServlet doGet: 14 44572400
I 2011-08-09 00:21:16.628 org.immopoly.appengine.CronjobServlet doGet: 15 51215791
I 2011-08-09 00:21:16.794 org.immopoly.appengine.CronjobServlet doGet: 16 58519949
I 2011-08-09 00:21:16.971 org.immopoly.appengine.CronjobServlet doGet: 17 61029407
I 2011-08-09 00:21:17.141 org.immopoly.appengine.CronjobServlet doGet: 18 59214360
I 2011-08-09 00:21:17.315 org.immopoly.appengine.CronjobServlet doGet: 19 57082222
I 2011-08-09 00:21:17.483 org.immopoly.appengine.CronjobServlet doGet: 20 60504455
I 2011-08-09 00:21:17.639 org.immopoly.appengine.CronjobServlet doGet: 21 49374409
I 2011-08-09 00:21:17.798 org.immopoly.appengine.CronjobServlet doGet: 22 60554343
I 2011-08-09 00:21:18.003 org.immopoly.appengine.CronjobServlet doGet: 23 56333970
I 2011-08-09 00:21:18.165 org.immopoly.appengine.CronjobServlet doGet: 24 60176856
I 2011-08-09 00:21:18.324 org.immopoly.appengine.CronjobServlet doGet: 25 48082835
I 2011-08-09 00:21:18.505 org.immopoly.appengine.CronjobServlet doGet: 26 60454177
I 2011-08-09 00:21:18.690 org.immopoly.appengine.CronjobServlet doGet: 27 60474823
I 2011-08-09 00:21:18.907 org.immopoly.appengine.CronjobServlet doGet: 28 60573117
I 2011-08-09 00:21:19.073 org.immopoly.appengine.CronjobServlet doGet: 29 60577528
I 2011-08-09 00:21:19.230 org.immopoly.appengine.CronjobServlet doGet: 30 60472583
I 2011-08-09 00:21:19.393 org.immopoly.appengine.CronjobServlet doGet: 31 58772323
I 2011-08-09 00:21:19.577 org.immopoly.appengine.CronjobServlet doGet: 32 60251677
I 2011-08-09 00:21:19.846 org.immopoly.appengine.CronjobServlet doGet: 33 60987182
I 2011-08-09 00:21:20.065 org.immopoly.appengine.CronjobServlet doGet: 34 60750163
I 2011-08-09 00:21:20.223 org.immopoly.appengine.CronjobServlet doGet: 35 60060429
I 2011-08-09 00:21:20.383 org.immopoly.appengine.CronjobServlet doGet: 36 56489364
I 2011-08-09 00:21:20.540 org.immopoly.appengine.CronjobServlet doGet: 37 56469965
I 2011-08-09 00:21:20.698 org.immopoly.appengine.CronjobServlet doGet: 38 61100093
I 2011-08-09 00:21:20.859 org.immopoly.appengine.CronjobServlet doGet: 39 58221762
I 2011-08-09 00:21:21.019 org.immopoly.appengine.CronjobServlet doGet: 40 51114330
I 2011-08-09 00:21:21.212 org.immopoly.appengine.CronjobServlet doGet: 41 59280103
I 2011-08-09 00:21:21.408 org.immopoly.appengine.CronjobServlet doGet: 42 58685377
I 2011-08-09 00:21:21.568 org.immopoly.appengine.CronjobServlet doGet: 43 39592247
I 2011-08-09 00:21:21.732 org.immopoly.appengine.CronjobServlet doGet: 44 43965744
I 2011-08-09 00:21:21.908 org.immopoly.appengine.CronjobServlet doGet: 45 61111418
I 2011-08-09 00:21:22.070 org.immopoly.appengine.CronjobServlet doGet: 46 61186005
I 2011-08-09 00:21:22.244 org.immopoly.appengine.CronjobServlet doGet: 47 61185396
I 2011-08-09 00:21:22.445 org.immopoly.appengine.CronjobServlet doGet: 48 59256965
I 2011-08-09 00:21:22.651 org.immopoly.appengine.CronjobServlet doGet: 49 47677964
I 2011-08-09 00:21:22.806 org.immopoly.appengine.CronjobServlet doGet: 50 61270274
I 2011-08-09 00:21:22.961 org.immopoly.appengine.CronjobServlet doGet: 51 61387462
I 2011-08-09 00:21:23.136 org.immopoly.appengine.CronjobServlet doGet: 52 55243637
I 2011-08-09 00:21:23.336 org.immopoly.appengine.CronjobServlet doGet: 53 61373408
I 2011-08-09 00:21:23.527 org.immopoly.appengine.CronjobServlet doGet: 54 61137417
I 2011-08-09 00:21:23.685 org.immopoly.appengine.CronjobServlet doGet: 55 61008937
I 2011-08-09 00:21:23.861 org.immopoly.appengine.CronjobServlet doGet: 56 61323626
I 2011-08-09 00:21:24.064 org.immopoly.appengine.CronjobServlet doGet: 57 61236046
I 2011-08-09 00:21:24.304 org.immopoly.appengine.CronjobServlet doGet: 58 61253959
I 2011-08-09 00:21:24.461 org.immopoly.appengine.CronjobServlet doGet: 59 61013510
I 2011-08-09 00:21:24.617 org.immopoly.appengine.CronjobServlet doGet: 60 60325253
I 2011-08-09 00:21:24.773 org.immopoly.appengine.CronjobServlet doGet: 61 61470834
I 2011-08-09 00:21:24.934 org.immopoly.appengine.CronjobServlet doGet: 62 61503849
I 2011-08-09 00:21:25.089 org.immopoly.appengine.CronjobServlet doGet: 63 61008983
I 2011-08-09 00:21:25.328 org.immopoly.appengine.CronjobServlet doGet: 64 60430709
I 2011-08-09 00:21:25.486 org.immopoly.appengine.CronjobServlet doGet: 65 61499741
I 2011-08-09 00:21:25.646 org.immopoly.appengine.CronjobServlet doGet: 66 61262989
I 2011-08-09 00:21:25.828 org.immopoly.appengine.CronjobServlet doGet: 67 61235943
I 2011-08-09 00:21:26.072 org.immopoly.appengine.CronjobServlet doGet: 68 61236102
I 2011-08-09 00:21:26.334 org.immopoly.appengine.CronjobServlet doGet: 69 61398107
I 2011-08-09 00:21:26.513 org.immopoly.appengine.CronjobServlet doGet: 70 61276585
I 2011-08-09 00:21:26.696 org.immopoly.appengine.CronjobServlet doGet: 71 61304424
I 2011-08-09 00:21:26.865 org.immopoly.appengine.CronjobServlet doGet: 72 61457151
I 2011-08-09 00:21:27.024 org.immopoly.appengine.CronjobServlet doGet: 73 61373324
I 2011-08-09 00:21:27.220 org.immopoly.appengine.CronjobServlet doGet: 74 29549940
I 2011-08-09 00:21:27.397 org.immopoly.appengine.CronjobServlet doGet: 75 45412020
I 2011-08-09 00:21:27.572 org.immopoly.appengine.CronjobServlet doGet: 76 61548366
I 2011-08-09 00:21:27.894 org.immopoly.appengine.CronjobServlet doGet: 77 61319417
I 2011-08-09 00:21:28.137 org.immopoly.appengine.CronjobServlet doGet: 78 61339011
I 2011-08-09 00:21:28.382 org.immopoly.appengine.CronjobServlet doGet: 79 61236097
I 2011-08-09 00:21:28.628 org.immopoly.appengine.CronjobServlet doGet: 80 59810863
I 2011-08-09 00:21:28.790 org.immopoly.appengine.CronjobServlet doGet: 81 61176683
I 2011-08-09 00:21:28.957 org.immopoly.appengine.CronjobServlet doGet: 82 60634317
I 2011-08-09 00:21:29.138 org.immopoly.appengine.CronjobServlet doGet: 83 60416292
I 2011-08-09 00:21:29.316 org.immopoly.appengine.CronjobServlet doGet: 84 61408478
I 2011-08-09 00:21:29.500 org.immopoly.appengine.CronjobServlet doGet: 85 61276130
I 2011-08-09 00:21:29.666 org.immopoly.appengine.CronjobServlet doGet: 86 60939836
I 2011-08-09 00:21:29.822 org.immopoly.appengine.CronjobServlet doGet: 87 61525093
I 2011-08-09 00:21:30.144 org.immopoly.appengine.CronjobServlet doGet: 88 61332347
I 2011-08-09 00:21:30.313 org.immopoly.appengine.CronjobServlet doGet: 89 61148187
I 2011-08-09 00:21:30.484 org.immopoly.appengine.CronjobServlet doGet: 90 61170454
I 2011-08-09 00:21:30.650 org.immopoly.appengine.CronjobServlet doGet: 91 61237428
I 2011-08-09 00:21:30.813 org.immopoly.appengine.CronjobServlet doGet: 92 61271569
I 2011-08-09 00:21:31.098 org.immopoly.appengine.CronjobServlet doGet: 93 61473926
I 2011-08-09 00:21:31.260 org.immopoly.appengine.CronjobServlet doGet: 94 54882486
I 2011-08-09 00:21:31.494 org.immopoly.appengine.CronjobServlet doGet: 95 61332825
I 2011-08-09 00:21:31.646 org.immopoly.appengine.CronjobServlet doGet: 96 60807661
I 2011-08-09 00:21:32.265 org.immopoly.appengine.CronjobServlet doGet: 97 61056251
I 2011-08-09 00:21:32.445 org.immopoly.appengine.CronjobServlet doGet: 98 61379760
I 2011-08-09 00:21:32.623 org.immopoly.appengine.CronjobServlet doGet: 99 61280234
I 2011-08-09 00:21:32.806 org.immopoly.appengine.CronjobServlet doGet: 100 58414052
I 2011-08-09 00:21:33.035 org.immopoly.appengine.CronjobServlet doGet: 101 50028212
I 2011-08-09 00:21:33.191 org.immopoly.appengine.CronjobServlet doGet: 102 61374465
I 2011-08-09 00:21:33.354 org.immopoly.appengine.CronjobServlet doGet: 103 56731895
I 2011-08-09 00:21:33.515 org.immopoly.appengine.CronjobServlet doGet: 104 61391284
I 2011-08-09 00:21:33.675 org.immopoly.appengine.CronjobServlet doGet: 105 55019288
I 2011-08-09 00:21:33.833 org.immopoly.appengine.CronjobServlet doGet: 106 61102226
I 2011-08-09 00:21:34.028 org.immopoly.appengine.CronjobServlet doGet: 107 61549895
I 2011-08-09 00:21:34.248 org.immopoly.appengine.CronjobServlet doGet: 108 61444152
I 2011-08-09 00:21:34.412 org.immopoly.appengine.CronjobServlet doGet: 109 61222712
I 2011-08-09 00:21:34.583 org.immopoly.appengine.CronjobServlet doGet: 110 60364057
I 2011-08-09 00:21:34.762 org.immopoly.appengine.CronjobServlet doGet: 111 61481196
I 2011-08-09 00:21:34.948 org.immopoly.appengine.CronjobServlet doGet: 112 61059843
I 2011-08-09 00:21:35.229 org.immopoly.appengine.CronjobServlet doGet: 113 61484757
I 2011-08-09 00:21:35.411 org.immopoly.appengine.CronjobServlet doGet: 114 61064644
I 2011-08-09 00:21:35.570 org.immopoly.appengine.CronjobServlet doGet: 115 60683625
I 2011-08-09 00:21:35.768 org.immopoly.appengine.CronjobServlet doGet: 116 56489379
I 2011-08-09 00:21:35.935 org.immopoly.appengine.CronjobServlet doGet: 117 57264228
I 2011-08-09 00:21:36.100 org.immopoly.appengine.CronjobServlet doGet: 118 61502826
I 2011-08-09 00:21:36.277 org.immopoly.appengine.CronjobServlet doGet: 119 61491595
I 2011-08-09 00:21:36.441 org.immopoly.appengine.CronjobServlet doGet: 120 61290010
I 2011-08-09 00:21:36.609 org.immopoly.appengine.CronjobServlet doGet: 121 61310395
I 2011-08-09 00:21:36.778 org.immopoly.appengine.CronjobServlet doGet: 122 61484754
I 2011-08-09 00:21:36.944 org.immopoly.appengine.CronjobServlet doGet: 123 43532062
I 2011-08-09 00:21:37.120 org.immopoly.appengine.CronjobServlet doGet: 124 61293330
I 2011-08-09 00:21:37.310 org.immopoly.appengine.CronjobServlet doGet: 125 61307714
I 2011-08-09 00:21:37.471 org.immopoly.appengine.CronjobServlet doGet: 126 61477883
I 2011-08-09 00:21:37.702 org.immopoly.appengine.CronjobServlet doGet: 127 61427197
I 2011-08-09 00:21:37.865 org.immopoly.appengine.CronjobServlet doGet: 128 61441079
I 2011-08-09 00:21:38.022 org.immopoly.appengine.CronjobServlet doGet: 129 61525130
I 2011-08-09 00:21:38.352 org.immopoly.appengine.CronjobServlet doGet: 130 57755699
I 2011-08-09 00:21:38.509 org.immopoly.appengine.CronjobServlet doGet: 131 61548858
I 2011-08-09 00:21:38.672 org.immopoly.appengine.CronjobServlet doGet: 132 61607420
I 2011-08-09 00:21:38.831 org.immopoly.appengine.CronjobServlet doGet: 133 61611521
I 2011-08-09 00:21:39.024 org.immopoly.appengine.CronjobServlet doGet: 134 61641069
I 2011-08-09 00:21:39.213 org.immopoly.appengine.CronjobServlet doGet: 135 52133829
I 2011-08-09 00:21:39.368 org.immopoly.appengine.CronjobServlet doGet: 136 61141347
I 2011-08-09 00:21:39.548 org.immopoly.appengine.CronjobServlet doGet: 137 61494350
I 2011-08-09 00:21:39.869 org.immopoly.appengine.CronjobServlet doGet: 138 57573078
I 2011-08-09 00:21:40.043 org.immopoly.appengine.CronjobServlet doGet: 139 61590998
I 2011-08-09 00:21:40.227 org.immopoly.appengine.CronjobServlet doGet: 140 61515812
I 2011-08-09 00:21:40.425 org.immopoly.appengine.CronjobServlet doGet: 141 61561223
I 2011-08-09 00:21:40.580 org.immopoly.appengine.CronjobServlet doGet: 142 61525065
I 2011-08-09 00:21:40.903 org.immopoly.appengine.CronjobServlet doGet: 143 47009782
I 2011-08-09 00:21:41.092 org.immopoly.appengine.CronjobServlet doGet: 144 61615303
I 2011-08-09 00:21:41.264 org.immopoly.appengine.CronjobServlet doGet: 145 61604357
I 2011-08-09 00:21:41.474 org.immopoly.appengine.CronjobServlet doGet: 146 41581205
I 2011-08-09 00:21:41.673 org.immopoly.appengine.CronjobServlet doGet: 147 61591414
I 2011-08-09 00:21:41.894 org.immopoly.appengine.CronjobServlet doGet: 148 61597825
I 2011-08-09 00:21:42.049 org.immopoly.appengine.CronjobServlet doGet: 149 61534739
I 2011-08-09 00:21:42.215 org.immopoly.appengine.CronjobServlet doGet: 150 61521062
I 2011-08-09 00:21:42.384 org.immopoly.appengine.CronjobServlet doGet: 151 61573040
I 2011-08-09 00:21:42.576 org.immopoly.appengine.CronjobServlet doGet: 152 61557853
I 2011-08-09 00:21:42.733 org.immopoly.appengine.CronjobServlet doGet: 153 61236099
I 2011-08-09 00:21:42.987 org.immopoly.appengine.CronjobServlet doGet: 154 61236002
I 2011-08-09 00:21:43.239 org.immopoly.appengine.CronjobServlet doGet: 155 60554612
I 2011-08-09 00:21:43.433 org.immopoly.appengine.CronjobServlet doGet: 156 61584571
I 2011-08-09 00:21:43.600 org.immopoly.appengine.CronjobServlet doGet: 157 61274964
I 2011-08-09 00:21:43.808 org.immopoly.appengine.CronjobServlet doGet: 158 61642178
I 2011-08-09 00:21:43.966 org.immopoly.appengine.CronjobServlet doGet: 159 61520419
I 2011-08-09 00:21:44.120 org.immopoly.appengine.CronjobServlet doGet: 160 61515301
I 2011-08-09 00:21:44.295 org.immopoly.appengine.CronjobServlet doGet: 161 61561524
I 2011-08-09 00:21:44.450 org.immopoly.appengine.CronjobServlet doGet: 162 61584167
I 2011-08-09 00:21:44.609 org.immopoly.appengine.CronjobServlet doGet: 163 61505050
I 2011-08-09 00:21:44.786 org.immopoly.appengine.CronjobServlet doGet: 164 61237030
I 2011-08-09 00:21:44.946 org.immopoly.appengine.CronjobServlet doGet: 165 61578517
I 2011-08-09 00:21:45.134 org.immopoly.appengine.CronjobServlet doGet: 166 61631367
I 2011-08-09 00:21:45.308 org.immopoly.appengine.CronjobServlet doGet: 167 61594217
I 2011-08-09 00:21:45.472 org.immopoly.appengine.CronjobServlet doGet: 168 58850753
I 2011-08-09 00:21:45.662 org.immopoly.appengine.CronjobServlet doGet: 169 61348903
I 2011-08-09 00:21:45.921 org.immopoly.appengine.CronjobServlet doGet: 170 49251387
I 2011-08-09 00:21:46.115 org.immopoly.appengine.CronjobServlet doGet: 171 61489401
I 2011-08-09 00:21:46.309 org.immopoly.appengine.CronjobServlet doGet: 172 60990617
I 2011-08-09 00:21:46.496 org.immopoly.appengine.CronjobServlet doGet: 173 61517928
I 2011-08-09 00:21:46.660 org.immopoly.appengine.CronjobServlet doGet: 174 61502813
I 2011-08-09 00:21:46.850 org.immopoly.appengine.CronjobServlet doGet: 175 60469180
I 2011-08-09 00:21:47.009 org.immopoly.appengine.CronjobServlet doGet: 176 60269603
I 2011-08-09 00:21:47.201 org.immopoly.appengine.CronjobServlet doGet: 177 61591021
I 2011-08-09 00:21:47.402 org.immopoly.appengine.CronjobServlet doGet: 178 61618592
I 2011-08-09 00:21:47.723 org.immopoly.appengine.CronjobServlet doGet: 179 55714782
I 2011-08-09 00:21:47.878 org.immopoly.appengine.CronjobServlet doGet: 180 51184638
I 2011-08-09 00:21:48.083 org.immopoly.appengine.CronjobServlet doGet: 181 61496182
I 2011-08-09 00:21:48.257 org.immopoly.appengine.CronjobServlet doGet: 182 49442107
I 2011-08-09 00:21:48.421 org.immopoly.appengine.CronjobServlet doGet: 183 61551474
I 2011-08-09 00:21:48.582 org.immopoly.appengine.CronjobServlet doGet: 184 61400157
I 2011-08-09 00:21:48.757 org.immopoly.appengine.CronjobServlet doGet: 185 41097916
I 2011-08-09 00:21:48.914 org.immopoly.appengine.CronjobServlet doGet: 186 43466526
I 2011-08-09 00:21:49.078 org.immopoly.appengine.CronjobServlet doGet: 187 61235996
I 2011-08-09 00:21:49.407 org.immopoly.appengine.CronjobServlet doGet: 188 61470521
I 2011-08-09 00:21:49.624 org.immopoly.appengine.CronjobServlet doGet: 189 61612778
I 2011-08-09 00:21:49.794 org.immopoly.appengine.CronjobServlet doGet: 190 61502816
I 2011-08-09 00:21:50.131 org.immopoly.appengine.CronjobServlet doGet: 191 61533646
I 2011-08-09 00:21:50.336 org.immopoly.appengine.CronjobServlet doGet: 192 61593347
I 2011-08-09 00:21:50.565 org.immopoly.appengine.CronjobServlet doGet: 193 61546293
I 2011-08-09 00:21:50.975 org.immopoly.appengine.CronjobServlet doGet: 194 61571158
I 2011-08-09 00:21:51.142 org.immopoly.appengine.CronjobServlet doGet: 195 61568659
I 2011-08-09 00:21:51.371 org.immopoly.appengine.CronjobServlet doGet: 196 61613981
I 2011-08-09 00:21:51.539 org.immopoly.appengine.CronjobServlet doGet: 197 60550141
I 2011-08-09 00:21:51.758 org.immopoly.appengine.CronjobServlet doGet: 198 61550074
I 2011-08-09 00:21:52.038 org.immopoly.appengine.CronjobServlet doGet: 199 61597450
I 2011-08-09 00:21:52.349 org.immopoly.appengine.CronjobServlet doGet: Wohnung 'Nachmieter gesucht !!!' vermietet. Provision überwiesen: 458.42 Eur
I 2011-08-09 00:21:52.740 org.immopoly.appengine.CronjobServlet doGet: 200 55619398
I 2011-08-09 00:21:52.964 org.immopoly.appengine.CronjobServlet doGet: 201 59111749
I 2011-08-09 00:21:53.134 org.immopoly.appengine.CronjobServlet doGet: 202 61606250
I 2011-08-09 00:21:53.305 org.immopoly.appengine.CronjobServlet doGet: 203 61611411
I 2011-08-09 00:21:53.521 org.immopoly.appengine.CronjobServlet doGet: 204 61515822
I 2011-08-09 00:21:53.707 org.immopoly.appengine.CronjobServlet doGet: 205 60642897
I 2011-08-09 00:21:53.892 org.immopoly.appengine.CronjobServlet doGet: 206 61611520
I 2011-08-09 00:21:54.120 org.immopoly.appengine.CronjobServlet doGet: 207 61280536
I 2011-08-09 00:21:54.301 org.immopoly.appengine.CronjobServlet doGet: 208 55485050
I 2011-08-09 00:21:54.479 org.immopoly.appengine.CronjobServlet doGet: 209 61008892
I 2011-08-09 00:21:54.677 org.immopoly.appengine.CronjobServlet doGet: 210 61488418
I 2011-08-09 00:21:54.839 org.immopoly.appengine.CronjobServlet doGet: 211 61494732
I 2011-08-09 00:21:55.028 org.immopoly.appengine.CronjobServlet doGet: 212 56489265
I 2011-08-09 00:21:55.218 org.immopoly.appengine.CronjobServlet doGet: 213 61636275
I 2011-08-09 00:21:55.394 org.immopoly.appengine.CronjobServlet doGet: Wohnung 'Designer Loft im DAZ mit Blick auf die Spree-Voll möbliert' vermietet. Provision überwiesen: 1
I 2011-08-09 00:21:55.704 org.immopoly.appengine.CronjobServlet doGet: update User
I 2011-08-09 00:21:55.706 org.immopoly.appengine.CronjobServlet doGet: Tagesabrechnung Miete: 3709.44 Eur
I 2011-08-09 00:21:55.706 org.immopoly.appengine.CronjobServlet doGet: Tagesabrechnung Provision: 1958.42 Eur
I 2011-08-09 00:21:55.846 org.immopoly.appengine.CronjobServlet doGet: save User
I 2011-08-09 00:21:55.952 org.immopoly.appengine.CronjobServlet doGet: finally

**Comment by stefanhoth** [comment]
@mrschtief closed

**Comment by stefanhoth** [comment]
@rob-bors reopen

**Comment by stefanhoth** [comment]
@rob-bors

mir wurden im history aber mehrere objekte als vermietet angezeigt. Uhrzeit 0:20 Uhr. Habe ein Screenshot, dass ich mrschtief gleich per mail sende. Gruß, immorob

**Comment by mrschtief** [comment]
wo kann man den hier attachments anhängen?

**Comment by yncyrydybyl** [comment]
XFILE 9023432
