### ISSUE TITLE
Beschreibungstext der App in Englisch

### ISSUE THREAD

**Issue by stefanhoth** [immopoly/immopoly#30]
@mackartor 
Kann einer von euch die Beschreibung des Spiels (http://immopoly.appspot.com/) mal in Englisch formulieren, damit auch Menschen die der deutschen Sprache nicht mächtig sind, auch einen Einblick bekommen.

**Comment by fama-berlin** [comment]
Ich hätte da mal was (auf Englisch) vorbereitet...

Wenn der Wunsch besteht, dann gebe ich das gerne frei.

**Comment by stefanhoth** [comment]
Hallo @fama-berlin, cool, klingt gut. Immer her damit!

**Comment by mackartor** [comment]
Hallo @fama-berlin gerne. Schließe mich an Stevie an.

**Comment by fama-berlin** [comment]
Gerne, aber wie mache ich das??? Ist das erste Mal für mich ;-)

**Comment by stefanhoth** [comment]
Hi, sorry, dass wir so lange nicht geantwortet haben - Wochenende usw.

Um Deine Frage zu beantworten, müsstest Du mir sagen, was genau Du vorbereitet hast. Ich habe gesehen, dass Du noch kein öffentliches Repository hast. Was hast Du also wo gemacht?

**Comment by fama-berlin** [comment]
Ich habe zuerst einmal den Text auf der appspot-Seite einfach einmal ins Englische gebracht.
Ich könnte also entweder den Text als File bereitstellen (Word, txt, was auch immer) oder ich könnte versuchen die Seite vom HTML her so wie sie jetzt schon ist, nachzubauen, so dass nur nich die Links angepasst werden müssen.

Ich kann erst wieder ab dem 4.10. reagieren, bin ein paar Tage nicht in Berlin.

**Comment by stefanhoth** [comment]
Hi,

der Text als Textfile würde uns schon helfen. Danke sehr!

**Comment by fama-berlin** [comment]
Hallo.

Nach längerer Abstinenz nun doch noch ein Lebenszeichen von mir...
ich habe sogar noch einen kleinen Einleitungstext geschriieben, damit das "Prinzip Immopoly" schon vorher erkannt werden kann.
Leider weiß ich nicht wie ich das Textfile hochgeladen bekomme. Auch die Suche (hier und bei Google) hat mir nicht wirklich weiter geholfen.
Muss ich das repo "forken" und dann neu einreichen? Oder geht das Ganze einfacher? Oder ganz anders?
