### ISSUE TITLE
notification by übernahmeversuch

### ISSUE THREAD

**Issue by yncyrydybyl** [immopoly/immopoly#32]
wenn jemand versucht hat die wohnung eines user zu übernehmen bekommt der user eine benachrichtigung.
nachrichten werden zusammengefasst, und der user wird in die history geführt.

**Comment by mrschtief** [comment]
GOLDeN TICKeT

**Comment by mrschtief** [comment]
prototyp implementiert, nach erfolgreicher anmeldung auf dem client wird beim c2dm registriert, diese registrationid wird per /user/C2DMregister an die appengine gesendet und dort im user profile gespeichert. per http://immopoly.appspot.com/user/C2DMsend?username=&message=helloWorld kann eine nachricht an den client gesendet werden, dort wird eine notification mit der message erstellt. ein click darauf führt zur immopoly app.

TODO's
Server:
- google oauth /relogin automatisieren
- spiellogik implementieren, nachricht bei übernahme versuch der eigenen wohnung

client:
- sprungziel in app definieren

**Comment by mrschtief** [comment]
spiellogik implementiert, nachricht bei übernahme versuch der eigenen wohnung.

commited

jetzt nur noch client stuff

**Comment by tobibo** [comment]
Definieren wohin gesprungen werden soll, am besten direkt zum expose oder ?

**Comment by mrschtief** [comment]
was machen wir bei mehreren.notifications? reicht nicht einfach in die app
rein? dann hat man gleich die karte und kann neue wohnungen nehmen
Am 16.11.2011 22:19 schrieb "tosa" <
reply@reply.github.com

**Comment by yncyrydybyl** [comment]
notification wird gesendet aber erscheint nicht auf dem empfänger

**Comment by mrschtief** [comment]
jetzt wird die c2dm registration id

**Comment by mrschtief** [comment]
nur noch bei login und register an server gesendet nicht bei getuserinof o_O
