### ISSUE TITLE
Eventing im Backend

### ISSUE THREAD

**Issue by mrschtief** [immopoly/immopoly#34]
Das Backend sollte eventbasiert sein und aktivitäten entkoppeln.

Beispiel: 
User versucht Wohnung zu übernehmen die bereits vergeben sind, er erhält negative Nachricht.
Die Aktionen die den Besitzer betreffen (Geld gutschreiben, benachrichtigen) sollte entkoppelt werden.

Dazu sollten im Backend Activities und Queues verwendet werden.

**Comment by mrschtief** [comment]
Task und TaskQueue in der AppEngine
http://code.google.com/appengine/docs/java/taskqueue/overview.html

**Comment by keyboardsurfer** [comment]
Backend wird neu geschrieben.
