### ISSUE TITLE
Keine neuen Wohnungen in Exposé aufnehmen

### ISSUE THREAD

**Issue by fama-berlin** [immopoly/immopoly#38]
Hallo noch einmal,
seit (ich glaube) gestern kann ich in mein Exposé keine neuen Wohnungen mehr aufnehmen.
Fehlermeldung: "Expose konnte nicht hinzugefügt werden".

Liegt das an meiner älteren Version von immopoly (siehe anderes Issue von mir)?
Gibt es neuerdings eine Wohnungsbegrenzung?

**Comment by mrschtief** [comment]
Habe ich gerade auch von bytye gehört und jetzt wieder zum laufen gebracht. anscheinend ist die neue anti Location Spoofing Server version nicht mit dem alten client kompatibel

**Comment by mrschtief** [comment]
fixed
