### ISSUE TITLE
badges for users

### ISSUE THREAD

**Issue by yncyrydybyl** [immopoly/immopoly#39]
it should be possible for a user to have badges.
such a badge needs to have a name, icon, description
there need to be a way to sign such a badge to a user

**Comment by yncyrydybyl** [comment]
the current list of ideas for badges can be found at https://github.com/immopoly/immopoly/wiki/Badges

**Comment by mrschtief** [comment]
So Badges sind drin und werden in der profile view angezeigt. jetzt kann das noch jemand hübsch machen, ich kümmere mich ab jetzt weiter um das backend und die generierung

**Comment by mrschtief** [comment]
backend iphone und android fertig
