### ISSUE TITLE
Historieneintrag mit Expose-Id 

### ISSUE THREAD

**Issue by mrschtief** [immopoly/immopoly#46]
die Historie braucht ein Feld für die Historien-Id um abgegebene Wohnungen oder Übernahmeversuche verlinken zu können

**Comment by mrschtief** [comment]
fixed

**Comment by stefanhoth** [comment]
Wie ist die Verlinkung nun gedacht?

**Comment by mrschtief** [comment]
entweder nach http://www.immobilienscout24.de/expose/61190284 oder
halt nach m.immobilienscout24.de

On Sun, Oct 30, 2011 at 4:24 PM, Stefan Hoth
reply@reply.github.com
wrote:

**Comment by stefanhoth** [comment]
Gibt es schon Promo-Keys damit wir eventuelle Affiliate-Sachen darüber laufen lassen können, die aus einem solchen Link resultieren?
