### ISSUE TITLE
Anzahl der Übernahmeversuche speichern

### ISSUE THREAD

**Issue by mrschtief** [immopoly/immopoly#47]
Im Expose sollte gespeichert werden wie oft man mit der Wohnung Geld verdient hat, dies kann dann auch in der Liste im client angezeigt werden.
Da fällt mir gleich ein tolles badge für ne Wohnung ein, die schon z.b. schon 10 mal versucht wurde zu übernehmen

**Comment by mrschtief** [comment]
im backend umgesetzt und wird jetzt auch schon per json ausgeliefert und kann vom client angezeigt werden.

**Comment by tresbjorn** [comment]
Anzahl der Versuche, Übernahmedatum, Raumzahl und m^2 werden geparst und angezeigt.
