### ISSUE TITLE
Startseite mit AJAX

### ISSUE THREAD

**Issue by mrschtief** [immopoly/immopoly#48]
Der variable Content der Startseite (TopX und Historie) sollte nicht per Ersetzung in der index.html durch das IndexServlet gemacht werden sondern mittels AJAX direkt über die API in JSON abgeholt und dann dargestellt werden.

Server:
- TopX Request
- History Request (mit optionaler UserId+Token, so dass der Request auch für die Clients verwendet werden kann)

Website:
- AJAX Request (siehe auch experimentallogin.html mit jquery)

**Comment by stefanhoth** [comment]
Ich übernehme das gern, sobald die Endpoints vorhanden sind. Vielleicht schaffe ich es diese Woche.

**Comment by mrschtief** [comment]
Backend fertig und dokumentiert https://github.com/immopoly/immopoly/wiki/ImmopolyAPI

http://immopoly.appspot.com/user/top?start=0&end=10

http://immopoly.appspot.com/user/history?start=0&end=10

**Comment by stefanhoth** [comment]
Doku hab ich mal leicht optimiert. Ich schau mal, wann ichs reinquetschen kann. Danke!

**Comment by mrschtief** [comment]
ist deployed und funktioniert +1
