### ISSUE TITLE
Anzahl Expose Flat in MapView

### ISSUE THREAD

**Issue by tobibo** [immopoly/immopoly#5]
Wir nehmen im Moment nur 4 \* 20 Wohnungen.

Wir müssen die Anzahl dynamischer laden. Eigentlich sind die Ergebnisse 1000 und mehr :)

**Comment by tresbjorn** [comment]
Es waren etwa 2950 im Umkreis von 3km ;-)

Die results sind zum Glück nach Entfernung sortiert.
Bei meinem Mitschnitt sind es 53(?) Wohnungen, die letzte
ist 0,71 km von der requesteten location entfernt.

Mit ein bisschen testen finden wir vllt nen guten wert für
den radius. 0,8? 1,0?

Vielleicht kann uns einer von Immoscout Jungs sagen, was 
man da so erwarten kann.
