### ISSUE TITLE
Anzahl der Exposés begrenzen

### ISSUE THREAD

**Issue by mrschtief** [immopoly/immopoly#50]
Um den Spielspaß zu erhöhen schlage ich vor die Anzahl der Exposes zu begrenzen.
- So wird man angehalten wirklich Wohnungen zu übernehmen, die demnächst vermietet werden.
- Die Abstoßen-Funktion macht richtig Sinn und wird mit ins Spielkonzept integriert
- Die Portfolioansicht wird häufiger benutzt, da man es versucht ständig zu optimieren
- Momentan werden schon die Anzahl der Übernahmeversuche gespeichert ( https://github.com/immopoly/immopoly/issues/47 ) anhand derer könnte man dan sein Portfoilo auch optimieren 
- Ressourcen sparen

Stevie meinte gestern wir sollten auf 30 reduzieren. Später können wir ja 30 im Umkreis einer Filiale machen.

**Comment by tobibo** [comment]
Wie per Email schon geschrieben. Level basierte Größe des Portfolios fände ich gut.

Je nach dem wie gut man im Spiel ist vergrößert sich auch das Portfolio, also am Anfang kann man evtl. nur 50 ( oder weniger) Wohnungen aufnehmen, macht man dan erste Gewinne durch Strafen, so steigt man im Level auf und bekommt auch mehr Platz im Portfolio. 

Der Mechanismus bzw. ein gute Größe fürs Level up ist natürlich wichtig. Evtl kann man da auch direkt ein Level-up kaufen im Game, also durch Spielgeld.

Wir sollten nochmal brainstormen zu dem Thema, finde es sehr spannen und denke Gerade die Spiele Faktoren müssen wir noch verbessern.

**Comment by stefanhoth** [comment]
Ich fordere Schaubilder, aber finde @tobibo's Idee gut. Auf jeden fall können wir aber erstmal die Begrenzung auf 30 einführen, da es die Taktik im Spiel erhöht. Das Leveling können wir danach einführen.

**Comment by mrschtief** [comment]
+1 ok ich bau dann die Begrenzung ein. und das Leveling können wir ja
über badges machen, dann müssen wir nicht noch ein Level system
nebenbei führen.

2011/11/24 Stefan Hoth
reply@reply.github.com:

**Comment by mrschtief** [comment]
auf 50 gesetzt
