### ISSUE TITLE
website mobil machen

### ISSUE THREAD

**Issue by mrschtief** [immopoly/immopoly#52]
Die Website geht mobil nicht richtig, css suckt und ajax request zeigen keine history an nur NaN

**Comment by stefanhoth** [comment]
Kümmere mich drum.

**Comment by mrschtief** [comment]
am besten auch gleich nochmal das gelb rausnehmen und irgend eine
andere evtl is24 farbe nehmen?

On Fri, Dec 2, 2011 at 5:43 PM, Stefan Hoth
reply@reply.github.com
wrote:

**Comment by mrschtief** [comment]
bitte auch noch das social dingends in der mobilen version ausblenden.

Wann kannste das machen? kümmere mich drum is ja schon wieder 4 tage her ;)

**Comment by stefanhoth** [comment]
Ich denke, ich kann mich morgen daran setzen.

**Comment by stefanhoth** [comment]
Auf dem Android-Browser ist nun die gesamte History auf undefined/NaN

**Comment by stefanhoth** [comment]
Parsing-Fehler ist bisher noch nicht erklärbar, aber der letzte Fix verhindert, dass ungültige Werte dargestellt werden. Nun ist auf Android die History aber nicht mehr sichtbar im Browser

**Comment by mrschtief** [comment]
Javascript errors in console http://www.nanaze.com/2009/01/debugging-javascript-on-android.html

**Comment by mrschtief** [comment]
Fehler trat heute bei IS24 auf, die benutzen firefox O_o und da steht in der console:

Fehler: setting a property that has only a getter
Quelldatei: http://immopoly.org/js/interactive.js
Zeile: 133 
        history = jsonData["org.immopoly.common.History"];

können wir damit was anfangen?

**Comment by stefanhoth** [comment]
Oh man, ich habe den Fehler dank dieser Meldung gefunden und nun läuft es sogar wieder auf dem Android.

Es war so einfach: Eine lokale Variable hieß "history", was in manchen Browsern (Android, Firefox) eine globale read-only Variable ist. Daher kam das Script ins stolpern, wenn es die History-Tabelle aufbauen sollte auf diesen Browsern.

Schön dass es gefixt ist.

**Comment by mrschtief** [comment]
yeah!!!!!!!

2012/2/9 Stefan Hoth
reply@reply.github.com:
