### ISSUE TITLE
Website auf eigenen Webserver auslagern

### ISSUE THREAD

**Issue by mrschtief** [immopoly/immopoly#53]
wir sollten die spielewebsite woanders auslagen damit wir nicht immer die appengine deployen müssen. wir greifen ja auf alle funktionen eh mit AJAX zu.
Ich hab mal immopoly.de angeschrieben immopoly.org is noch frei

**Comment by yncyrydybyl** [comment]
mal schaun ob da jemand antwortet ansonsten waere ja auch noch immopoly.mobi frei.

**Comment by mrschtief** [comment]
immopoly.org is am start und das website repo wieder reanimiert, das wird dort hin automatisch deployed...

letztes problem mit javascript siehe #59
