### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by mrschtief** [immopoly/immopoly#59]
- das "website" repository ist wieder reanimiert
  - Jeder commit wird gleich auf immopoly.org gepushed

Zum letzten Punkt jetzt eine Frage an die Javascript Experten. in der
HTML-Seite auf immopoly.org lade ich das immopoly.js von
immopoly.appspot.com. darin wird ein AJAX-Request an
immopoly.appspot.com gemacht um die Top User und History zu holen. Nun
bekommen wir trotzdem ein

"XMLHttpRequest cannot load
http://immopoly.appspot.com/user/history?start=0&end=10. Origin
http://immopoly.org is not allowed by Access-Control-Allow-Origin."

Hat jemand eine Idee? T meinte irgendwas mit JSONP, also noch ein
funktionsaufruf drumrum...

Stevie z.B., kannst du helfen und das immopoly.js entsprechend
anpassen, oder sagen was zu tun ist?

**Comment by mrschtief** [comment]
@stefanhoth  schrieb dazu 

Aaaaalso: Cross-Domain-Zugriffe bleiben Cross-Domain-Zugriffe, auch wenn Du das Javascript aus der Cross-Domain lädst, denn es bleibt so, dass ein Ajax-Zugriff auf eine von der aktuell besuchten (immopoly.org) abweicht (immopoly.appspot.com).

Es gibt dafür 2 bekannte Lösungen:
1. Proxy

Statt die AJAX-Anfrage direkt an immopoly.appspot.com zu stellen wird die Anfrage an ein proxy-Script auf immopoly.org geschickt, welches seinerseits die Anfrage an immopoly.appspot.com schickt und das Ergebnis dann an den Client weiterreicht (und sogar cachen könnte).

Dazu notwendig:
- Proxy-Script, welches auf immopoly.org laufen kann und die o.g. Funktionen ausführt.
- Änderung des Website-Scripts, dass es mit immopoly.org redet
1. JSONP

Es gibt eine häßliche und halbgefährliche Krücke namens JSONP. Dabei wird statt reinem JSON-Text eine dynamisch generierte Script-Datei geladen, die im Prinzip nichts anderes ist als der "alte" JSON-Text umgeben von einer Funktion mit einem Namen, der vom Client übergeben wird.

vorher:
http://immopoly.appspot.com/user/history?start=0&end=10
{ id: "stevie", skill: 1000 }

dann:
http://immopoly.appspot.com/user/history?start=0&end=10&callback=?
func2353({ id: "stevie", skill: 1000 })

Der Name der Funktion wird an die Stelle des Fragezeichens von jQuery beim Zugriff automatisch/dynamisch gesetzt und muss serverseitig als GET-Param ausgelesen werden.

(Genauere Erklärung in PHP http://www.fbloggs.com/2010/07/09/how-to-access-cross-domain-data-with-ajax-using-jsonp-jquery-and-php/ )

Problematisch/potenziell gefährlich ist es, weil der Code vom Server geladen und clientseitig sofort zur Ausführung gelangt. Ansonsten ist es eine anerkannte Krücke für die Umgehung der Same-Origin-Policy.

Dazu notwendig:
- Serverseitige Anpassung der Restcalls, um wahlweise auch JSONP-calls korrekt zu beantworten (GET-Parameter "callback" vorhanden)
- minimale Anpassung des Website-JS, um die Call auf JSONP statt XHR laufen zu lassen.

Ich hoffe Licht ins Dunkel gebracht zu haben und votiere für Variante 1 sofern der Webspace das hergibt.

Eure Wahl?
- stevie

**Comment by mrschtief** [comment]
@tresbjorn schrieb dazu

 Sieht aus, als könnte auch ein

resp.setHeader( "Access-Control-Allow-Origin", "*" )
oder
resp.setHeader( "Access-Control-Allow-Origin", "http://immopoly.org" )

Im history-servlet helfen.
Sagt zumindest https://developer.mozilla.org/En/HTTP_access_control

Weiß aber nicht, ob das alle browser unterstützen?

**Comment by stefanhoth** [comment]
@mrschtief Kannst Du mir mal sagen, was auf dem Host von immopoly.org möglich ist? Kann man da PHP oder so laufen lassen?

**Comment by mrschtief** [comment]
jepp php ist möglich, ist ein "1&1 Dual Perfect" leider kann ich nur
FTP Zugriffe vergeben.

Aber ein Commit wird nach ein paar Minuten gepusht

Meinst du proxying macht Sinn? da wir ja requests mit verschiedenen
urls machen /user /...

On Thu, Feb 2, 2012 at 3:03 PM, Stefan Hoth
reply@reply.github.com
wrote:

**Comment by stefanhoth** [comment]
Ich dachte es geht um die beiden requests auf der Startseite? Die sind doch für alle Besucher gleich.

Proxy wäre die sauberste und einfachste Lösung und hätte den Vorteil, dass wir cachen könnten, um API-Requests zu sparen.

**Comment by mrschtief** [comment]
stimmt auch wieder, aber dann müssen wir bei allen zukünftigen request
für die startseite immer ein proxy rumbauen, obwohl wir dann auch noch
genauer tracken könnten.

es gibt doch sicher standardproxylösungen dafür oder?

On Thu, Feb 2, 2012 at 3:57 PM, Stefan Hoth
reply@reply.github.com
wrote:

**Comment by stefanhoth** [comment]
Funzt
