### ISSUE TITLE
Android alpha version not installable on HC Desire Z running Android 2.3.3

### ISSUE THREAD

**Issue by jukey** [immopoly/immopoly#61]
The package installer shows an Error: No installed

Any idea for investigation?

**Comment by keyboardsurfer** [comment]
Plug it into your development machine's USB-port, type `adb logcat` repeat the installation process and post the result here.

**Comment by mrschtief** [comment]
maybe you have an old version installed? try removing first

**Comment by jukey** [comment]
You are right removing the old version first and installing the new version second worked fine
