### ISSUE TITLE
Put explanation: "remove older versons first" next to the "Download der ALPHA-Version" button 

### ISSUE THREAD

**Issue by jukey** [immopoly/immopoly#62]
At the moment there is a text next to the button:
"Achtung! Diese Version ist top-aktuell und beinhaltet damit die neuesten Funktionen und Layouts. Da sie aber noch nicht ausreichend getestet ist, kann es zu Abstürzen oder anderen Fehlfunktionen kommen. Wenn Du Fehler findest, hilfst Du uns sehr, wenn Du diese meldest."

suggestion for a version that explains better that uninstalling is neacessary:
"<b>Achtung! Bitte deinstalliere Immopoly bevor du die ALPHA-Version ausprobierst!</b> Diese Version ist top-aktuell und beinhaltet damit die neuesten Funktionen und Layouts. Da sie aber noch nicht ausreichend getestet ist, kann es zu Abstürzen oder anderen Fehlfunktionen kommen. Wenn Du Fehler findest, hilfst Du uns sehr, wenn Du diese meldest."

**Comment by mrschtief** [comment]
deinstallieren ist nicht nötig, da gleicher Key wie auf dem market

**Comment by stefanhoth** [comment]
Mittlerweile stimmt das und daher denke ich, dass der Hinweis nicht mehr nötig ist. Mit einer sehr alten Version könnte aber eine Deinstallation notwendig sein.

Danke @jukey.
