### ISSUE TITLE
evtl. fehlerhafte Anzeige?

### ISSUE THREAD

**Issue by ghost** [immopoly/immopoly#65]
Teilweise werden nicht alle Wohnungen aus dem Portfolio als solche angezeigt. Bspw. kann ich bei der Wohnung mit der Scout-ID: 63797982 eine "Übernahme versuchen" und erhalte die Meldung: <i>Die Wohnung ist bereits in deinem Portfolio!</i> - "Wohnung abgeben" ist gar nicht möglich. <i>(Android)</i>

**Comment by ghost** [comment]
[Update]: Sorry - besagte Wohnungen sind tatsächlich nicht im Portfolio, doch warum dann diese Meldung? Zudem erhalte ich Belohnungen für Wohnungen, die ich nicht mehr im Portfolio habe (ups - verraten).

**Comment by keyboardsurfer** [comment]
Viel Spaß mit den Belohnungen. Danke fürs Melden. Wenn's stört bitte erneut [hier melden](https://github.com/immopoly/android/issues/new).
