### ISSUE TITLE
Doppelte Anzahl der gemieteten Wohnungen - Bug

### ISSUE THREAD

**Issue by K2DaC** [immopoly/immopoly#68]
Gelegentlich habe ich einen Bug, der dazu führt, dass alle gemieteten Wohnungen doppelt angezeigt werden.
Sowohl im Info PopUp, als auch in der Liste.

Screen PopUp : http://podkowik.tk/immobug.png (78 / 50 Wohnungen, die hab ich devinitiv nicht)
Screen Liste : http://podkowik.tk/doppelt-immo.png (Alle Wohnungen sind doppelt, nicht untereinandern, sondern wahllos)

Hoffe mir wird nicht auch die Miete doppelt abgezogen :X

Fehler tritt nur auf, wenn man über eine Push-Notification in die App geht. 
Wenn man die App komplett beendet, und über das Icon startet, tritt der fehler nicht auf.

FIX PLX :P

**Comment by mrschtief** [comment]
wurde gefixt, Danke für den Report. Bitte mal die neue Alpha Version von immopoly.org/donwload holen 

https://github.com/immopoly/android/issues/72
